name = "backend"
main = "src/index.ts"
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# These must match your .env values
DATABASE_URL="prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..IMtNHqsvEXTIKQNI3tg5Iz9PtOU2PRvAWeeLMUDdZ6A"